### ISSUE TITLE
TypeError with --dataParallel training

### ISSUE THREAD

**Issue by markusdr** [ucfnlp/control-over-copying#6]
I'm trying to run data-parallel training on a machine with 4 GPUs. However, it aborts after a random number of batches during the first epoch with an error message:

    $ python run.py --do_train --train_prefix data/train --valid_prefix data/valid --dataParallel
    ...    
    86.5112 : Epoch  1, Batch    173, Loss  3.771451, Average Loss  4.156217, Time  0.256750
    Traceback (most recent call last):
      File "run.py", line 479, in <module>
        main()
      File "run.py", line 473, in main
        train(args)
      File "run.py", line 119, in train
        loss = lossFunc(predicts, labels, n_token).sum()
      File "/home/ec2-user/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/ec2-user/control-over-copying/parallel.py", line 151, in forward
        outputs = _criterion_parallel_apply(replicas, inputs, targets, kwargs)
      File "/home/ec2-user/control-over-copying/parallel.py", line 211, in _criterion_parallel_apply
        raise output
      File "/home/ec2-user/control-over-copying/parallel.py", line 186, in _worker
        output = module(*(input + target), **kwargs)
    TypeError: KLDivLoss object argument after ** must be a mapping, not NoneType

**Comment by markusdr** [comment]
Looks like I can avoid the error by choosing a different batch size.

**Comment by KaiQiangSong** [comment]
> Looks like I can avoid the error by choosing a different batch size.

That's weird. Sorry, I couldn't recognize the issue you mentioned with the error message only. I didn't have this problem when I trained my model.
I suggest you use the batch_size to be multiple of N and large or equal than N. Where N is the number of GPUs you are using for training. That might help.
